version: 1.10.0.{build}
image:
  - Visual Studio 2022
  - Ubuntu
  - macOS
  - macOS-Monterey
  - macOS-Bigsur
configuration: Release
skip_commits:
  message: /.*\[ci\-skip\].*/ 
before_build:
  - dotnet restore src/Vlingo.Xoom.UUID.sln
build:
  project: src/Vlingo.Xoom.UUID.sln
  verbosity: minimal
  publish_nuget: true
test_script:
  - dotnet test src/Vlingo.Xoom.UUID.Tests
deploy:
  - provider: NuGet
    api_key:
      secure: 4VJZEFZNaDrk3FJmRSmBW+wQugDoPi6DtVlsLZ+26IOo+wb0u9JlnTOTQF+NXs2s
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      branch: master
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/37621a855e91c31ab1da
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
